language: node_js

sudo: false

node_js:
- '4'

branches:
  only:
  - master
  
cache:
  directories:
  - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_2f598e748b08_key -iv $encrypted_2f598e748b08_iv
  -in id_rsa_travis.enc -out id_rsa_travis -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'lchord'
- git config --global user.email 569187749@qq.com
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-generator-sitemap --save
- npm install hexo-deployer-git --save
script:
- hexo clean
- hexo g
- hexo d
