language: node_js
sudo: false
node_js:
- '4'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- git config --global user.name 'lchord'
- git config --global user.email 569187749@qq.com
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-generator-sitemap --save
- npm install hexo-renderer-scss --save
- npm install hexo-deployer-git --save
script:
- hexo clean
- hexo g
- hexo d
