language: node_js

sudo: false

node_js:
- '8'

branches:
  only:
  - master

cache:
  directories:
  - node_modules
  - ~/.npm

# S: Build Lifecycle
before_install:
- git config --global user.name 'lchord'
- git config --global user.email 569187749@qq.com

install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-generator-sitemap --save
- npm install hexo-renderer-scss --save
- npm install hexo-deployer-git --save
- npm install gulp --save
- npm install gulp-htmlclean --save
- npm install gulp-htmlmin --save
- npm install gulp-minify-css --save
- npm install gulp-uglify --save

script:
- hexo clean
- hexo g
- gulp

after_script:
  - cd ./public
  - git init
  - git add .
  - git commit -m "Travis"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

env:
 global:
   - GH_REF: github.com/lchord/lchord.github.io.git

