language: node_js
sudo: false
node_js:
  - '8'
branches:
  only:
    - master
cache:
  directories:
  - node_modules
  - "~/.npm"
before_install:
  - openssl aes-256-cbc -K $encrypted_faa615a31f06_key -iv $encrypted_faa615a31f06_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - chmod +x after_script.sh
  - mv id_rsa ~/.ssh/
  - chmod 600 ~/.ssh/id_rsa
  - npm install
install:
  - cat travis-pubkey.txt >> ~/.ssh/known_hosts
script:
  - git clone https://github.com/lchord/find.git themes/find
  - hexo clean
  - hexo g
  - gulp
after_script:
  - ./after_script.sh
