language: node_js
sudo: false
node_js:
  - '10'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
    - "~/.npm"
before_install:
  - openssl aes-256-cbc -K $encrypted_faa615a31f06_key -iv $encrypted_faa615a31f06_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - chmod +x after_script.sh
  - mv id_rsa ~/.ssh/
  - chmod 600 ~/.ssh/id_rsa
  - cat travis-pubkey.txt >> ~/.ssh/known_hosts
install:
  - npm install
script:
  - git clone https://{$THEME_STRING}@github.com/lchord/hexo-theme-journal.git themes/hexo-theme-journal
  - hexo clean
  - hexo g
  - gulp
after_script:
  - ./after_script.sh
